#!/usr/bin/env python3
"""
Script to map old localization keys to new camelCase property names
"""

# Mapping from old 'key_name' to new 'keyName' (camelCase)
MAPPING = {
    'app_title': 'appTitle',
    'saved_servers': 'savedServers',
    'add_server': 'addServer',
    'no_servers': 'noServers',
    'add_server_to_start': 'addServerToStart',
    'server_name': 'serverName',
    'ip_address': 'ipAddress',
    'port': 'port',
    'username': 'username',
    'password': 'password',
    'add_new_server': 'addNewServer',
    'edit_server': 'editServer',
    'save': 'save',
    'cancel': 'cancel',
    'delete_server': 'deleteServer',
    'delete_confirm': 'deleteConfirm',
    'delete': 'delete',
    'edit': 'edit',
    'active': 'active',
    'mock_mode': 'mockMode',
    'mock_mode_desc': 'mockModeDesc',
    'logout': 'logout',
    'logout_confirm': 'logoutConfirm',
    'nav_dashboard': 'navDashboard',
    'nav_extensions': 'navExtensions',
    'nav_calls': 'navCalls',
    'nav_queues': 'navQueues',
    'nav_reports': 'navReports',
    'dashboard': 'dashboard',
    'extensions': 'extensions',
    'active_calls': 'activeCalls',
    'queues': 'queues',
    'waiting': 'waiting',
    'available': 'available',
    'call': 'call',
    'online': 'online',
    'offline': 'offline',
    'recent_calls': 'recentCalls',
    'no_active_calls': 'noActiveCalls',
    'duration': 'duration',
    'cdr_title': 'cdrTitle',
    'record_count': 'recordCount',
    'records': 'records',
    'export_csv': 'exportCsv',
    'answered': 'answered',
    'no_answer': 'noAnswer',
    'busy': 'busy',
    'failed': 'failed',
    'status': 'status',
    'no_records': 'noRecords',
    'loading_error': 'loadingError',
    'retry_button': 'retryButton',
    'filter_calls': 'filterCalls',
    'date_range': 'dateRange',
    'from_date': 'fromDate',
    'to_date': 'toDate',
    'source_number': 'sourceNumber',
    'destination_number': 'destinationNumber',
    'call_status': 'callStatus',
    'all': 'all',
    'apply_filter': 'applyFilter',
    'saved': 'saved',
    'save_error': 'saveError',
    'file_saved': 'fileSaved',
    'path': 'path',
    'file_save_error': 'fileSaveError',
    'saving': 'saving',
    'filter': 'filter',
    'field_required': 'fieldRequired',
    'name_required': 'nameRequired',
    'ip_required': 'ipRequired',
    'port_required': 'portRequired',
    'overall_stats': 'overallStats',
    'last_updated': 'lastUpdated',
    'average_wait': 'averageWait',
    'seconds': 'seconds',
    'view_all': 'viewAll',
    'auto_refresh': 'autoRefresh',
    'interval': 'interval',
    'retry': 'retry',
    'loading': 'loading',
    'error': 'error',
    'refresh': 'refresh',
    'settings': 'settings',
    'language': 'language',
    'theme': 'theme',
    'light': 'light',
    'dark': 'dark',
    'system': 'system',
}

# Print mapping
print("Key Mapping:")
print("=" * 80)
for old_key, new_key in sorted(MAPPING.items()):
    print(f"l10n.t('{old_key}')  →  l10n!.{new_key}")
