// Mocks generated by Mockito 5.4.6 from annotations
// in astrix_assist/test/unit/data/datasources/ssh_system_datasource_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:astrix_assist/core/services/asterisk_ssh_manager.dart' as _i5;
import 'package:astrix_assist/core/services/script_models.dart' as _i4;
import 'package:astrix_assist/core/ssh_config.dart' as _i2;
import 'package:astrix_assist/core/ssh_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSshConfig_0 extends _i1.SmartFake implements _i2.SshConfig {
  _FakeSshConfig_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSshService_1 extends _i1.SmartFake implements _i3.SshService {
  _FakeSshService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeScriptResponse_2<T> extends _i1.SmartFake
    implements _i4.ScriptResponse<T> {
  _FakeScriptResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AsteriskSshManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockAsteriskSshManager extends _i1.Mock
    implements _i5.AsteriskSshManager {
  MockAsteriskSshManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SshConfig get config =>
      (super.noSuchMethod(
            Invocation.getter(#config),
            returnValue: _FakeSshConfig_0(this, Invocation.getter(#config)),
          )
          as _i2.SshConfig);

  @override
  _i3.SshService get sshService =>
      (super.noSuchMethod(
            Invocation.getter(#sshService),
            returnValue: _FakeSshService_1(
              this,
              Invocation.getter(#sshService),
            ),
          )
          as _i3.SshService);

  @override
  _i6.Future<void> connect() =>
      (super.noSuchMethod(
            Invocation.method(#connect, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> ensureScriptDeployed() =>
      (super.noSuchMethod(
            Invocation.method(#ensureScriptDeployed, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i4.ScriptResponse<_i4.SystemInfo>> getSystemInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getSystemInfo, []),
            returnValue: _i6.Future<_i4.ScriptResponse<_i4.SystemInfo>>.value(
              _FakeScriptResponse_2<_i4.SystemInfo>(
                this,
                Invocation.method(#getSystemInfo, []),
              ),
            ),
          )
          as _i6.Future<_i4.ScriptResponse<_i4.SystemInfo>>);

  @override
  _i6.Future<_i4.ScriptResponse<_i4.CdrListResponse>> getCdrs({
    int? days = 7,
    int? limit = 1000,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCdrs, [], {#days: days, #limit: limit}),
            returnValue:
                _i6.Future<_i4.ScriptResponse<_i4.CdrListResponse>>.value(
                  _FakeScriptResponse_2<_i4.CdrListResponse>(
                    this,
                    Invocation.method(#getCdrs, [], {
                      #days: days,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i4.ScriptResponse<_i4.CdrListResponse>>);

  @override
  _i6.Future<_i4.ScriptResponse<_i4.RecordingsListResponse>> getRecordings({
    int? days = 7,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRecordings, [], {#days: days}),
            returnValue:
                _i6.Future<
                  _i4.ScriptResponse<_i4.RecordingsListResponse>
                >.value(
                  _FakeScriptResponse_2<_i4.RecordingsListResponse>(
                    this,
                    Invocation.method(#getRecordings, [], {#days: days}),
                  ),
                ),
          )
          as _i6.Future<_i4.ScriptResponse<_i4.RecordingsListResponse>>);

  @override
  _i6.Future<_i4.ScriptResponse<_i4.AmiStatus>> checkAmi() =>
      (super.noSuchMethod(
            Invocation.method(#checkAmi, []),
            returnValue: _i6.Future<_i4.ScriptResponse<_i4.AmiStatus>>.value(
              _FakeScriptResponse_2<_i4.AmiStatus>(
                this,
                Invocation.method(#checkAmi, []),
              ),
            ),
          )
          as _i6.Future<_i4.ScriptResponse<_i4.AmiStatus>>);

  @override
  _i6.Future<_i4.ScriptResponse<_i4.AmiCredentials>> setupAmi({
    String? username = 'astrix_assist',
    String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setupAmi, [], {
              #username: username,
              #password: password,
            }),
            returnValue:
                _i6.Future<_i4.ScriptResponse<_i4.AmiCredentials>>.value(
                  _FakeScriptResponse_2<_i4.AmiCredentials>(
                    this,
                    Invocation.method(#setupAmi, [], {
                      #username: username,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i4.ScriptResponse<_i4.AmiCredentials>>);

  @override
  _i6.Future<dynamic> downloadRecording(
    String? remotePath, {
    String? localPath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadRecording,
              [remotePath],
              {#localPath: localPath},
            ),
            returnValue: _i6.Future<dynamic>.value(),
          )
          as _i6.Future<dynamic>);
}
