// Mocks generated by Mockito 5.4.6 from annotations
// in astrix_assist/test/unit/data/repositories/cdr_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:astrix_assist/core/services/asterisk_ssh_manager.dart' as _i2;
import 'package:astrix_assist/data/datasources/ssh_cdr_datasource.dart' as _i3;
import 'package:astrix_assist/data/models/cdr_model.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAsteriskSshManager_0 extends _i1.SmartFake
    implements _i2.AsteriskSshManager {
  _FakeAsteriskSshManager_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SshCdrDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSshCdrDataSource extends _i1.Mock implements _i3.SshCdrDataSource {
  MockSshCdrDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AsteriskSshManager get sshManager =>
      (super.noSuchMethod(
            Invocation.getter(#sshManager),
            returnValue: _FakeAsteriskSshManager_0(
              this,
              Invocation.getter(#sshManager),
            ),
          )
          as _i2.AsteriskSshManager);

  @override
  _i4.Future<List<_i5.CdrModel>> getCdrRecords({
    DateTime? startDate,
    DateTime? endDate,
    String? src,
    String? dst,
    String? disposition,
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCdrRecords, [], {
              #startDate: startDate,
              #endDate: endDate,
              #src: src,
              #dst: dst,
              #disposition: disposition,
              #limit: limit,
            }),
            returnValue: _i4.Future<List<_i5.CdrModel>>.value(<_i5.CdrModel>[]),
          )
          as _i4.Future<List<_i5.CdrModel>>);

  @override
  _i4.Future<_i5.CdrModel?> getCdrByUniqueId(String? uniqueId) =>
      (super.noSuchMethod(
            Invocation.method(#getCdrByUniqueId, [uniqueId]),
            returnValue: _i4.Future<_i5.CdrModel?>.value(),
          )
          as _i4.Future<_i5.CdrModel?>);
}
