// Mocks generated by Mockito 5.4.6 from annotations
// in astrix_assist/test/unit/core/services/asterisk_ssh_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i3;

import 'package:astrix_assist/core/ssh_config.dart' as _i2;
import 'package:astrix_assist/core/ssh_service.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSshConfig_0 extends _i1.SmartFake implements _i2.SshConfig {
  _FakeSshConfig_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFile_1 extends _i1.SmartFake implements _i3.File {
  _FakeFile_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SshService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSshService extends _i1.Mock implements _i4.SshService {
  MockSshService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SshConfig get config =>
      (super.noSuchMethod(
            Invocation.getter(#config),
            returnValue: _FakeSshConfig_0(this, Invocation.getter(#config)),
          )
          as _i2.SshConfig);

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  _i5.Future<bool> isConnectionHealthy() =>
      (super.noSuchMethod(
            Invocation.method(#isConnectionHealthy, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> connect() =>
      (super.noSuchMethod(
            Invocation.method(#connect, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> fileExists(String? remotePath) =>
      (super.noSuchMethod(
            Invocation.method(#fileExists, [remotePath]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<List<String>> listRecordings(String? date) =>
      (super.noSuchMethod(
            Invocation.method(#listRecordings, [date]),
            returnValue: _i5.Future<List<String>>.value(<String>[]),
          )
          as _i5.Future<List<String>>);

  @override
  _i5.Future<_i3.File> downloadRecording(
    String? remotePath, {
    String? localPath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadRecording,
              [remotePath],
              {#localPath: localPath},
            ),
            returnValue: _i5.Future<_i3.File>.value(
              _FakeFile_1(
                this,
                Invocation.method(
                  #downloadRecording,
                  [remotePath],
                  {#localPath: localPath},
                ),
              ),
            ),
          )
          as _i5.Future<_i3.File>);

  @override
  _i5.Future<_i3.File?> downloadRecordingByUniqueId(
    String? uniqueid,
    String? callDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#downloadRecordingByUniqueId, [
              uniqueid,
              callDate,
            ]),
            returnValue: _i5.Future<_i3.File?>.value(),
          )
          as _i5.Future<_i3.File?>);

  @override
  _i5.Future<String> executeCommand(String? command) =>
      (super.noSuchMethod(
            Invocation.method(#executeCommand, [command]),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#executeCommand, [command]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<bool> testConnection() =>
      (super.noSuchMethod(
            Invocation.method(#testConnection, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}
